### ISSUE TITLE
weird error since last update

### ISSUE THREAD

**Issue by japel** [ptarjan/node-cache#51] opened 2015-06-09 09:29 UTC
hey there!
I was using version 0.1.2 and everything was working fine.
As I updated today to version 0.1.3 I cannot longer retrieve stored key value pairs.

This is what worked on 0.1.2 and is not working in 0.1.3 anymore:

```javascript
//myAwesomeJSFile1.js
var myAwesomeCache = require("memory-cache");
myAwesomeCache.put("myKey","myValue");

//myAwesomeJSFile2.js
var myAwesomeCache = require("memory-cache");
console.log(myAwesomeCache.get("myKey")); 
//prints "myValue" in 0.1.2
//prints null in 0.1.3
```
does it maybe have something to do with the added parameter validation?

Best regards!

**Comment by jwngr** [comment] 2015-06-09 17:10
Yup, this was my fault caused by #48. PR with a fix is incoming.

**Closed** 2015-06-09 17:23 UTC
